-- Wirely product seed data
-- Run after 001_initial.sql in Supabase Dashboard → SQL Editor

insert into public.products (
  slug,
  name,
  short_name,
  price,
  compare_at_price,
  badge,
  description,
  meta_title,
  meta_description,
  video_url,
  video_thumbnail,
  highlights,
  images,
  device_compatibility,
  stock,
  sort_order,
  is_active
)
values
  (
    '40w-charger',
    '40W Dynamic Power Adapter with 60W Max',
    '40W Power Adapter',
    3599,
    null,
    'Best Seller',
    'Apple 40W USB-C Dynamic Power Adapter delivers fast, efficient charging for your iPhone 15/16 series and MacBook Air. With 60W max output, it dynamically adjusts power delivery for optimal charging speed and safety.',
    '40W iPhone Charger Pakistan | Wirely',
    'Buy genuine 40W USB-C power adapter for iPhone 15/16 in Pakistan. Free nationwide delivery from Wirely.',
    null,
    null,
    '["40W standard / 60W max dynamic output","USB-C Power Delivery for iPhone & MacBook","Compact, travel-friendly design","Built-in safety: overheat, overcurrent, short-circuit protection","Compatible with all USB-C devices"]'::jsonb,
    '["/products/40w-charger.jpeg","/products/40w-charger-alt.jpeg"]'::jsonb,
    '[{"icon":"📱","name":"iPhone","models":"iPhone 15, 15 Pro, 16, 16 Pro, 16e"},{"icon":"💻","name":"MacBook","models":"MacBook Air M1/M2/M3"},{"icon":"📱","name":"iPad","models":"iPad Pro, iPad Air (USB-C)"},{"icon":"⌚","name":"Apple Watch","models":"Series 7+ (with USB-C cable)"}]'::jsonb,
    50,
    0,
    true
  ),
  (
    'usb-c-cable',
    'USB-C Fast Charging & Data Cable (1m)',
    'USB-C Cable (1m)',
    1599,
    null,
    null,
    'Apple USB-C Charge Cable (1m) supports up to 60W fast charging and high-speed data transfer. Braided, durable design built to last with every iPhone 15/16 and USB-C device.',
    'USB-C Cable 1m Pakistan | Wirely',
    'Durable 60W USB-C to USB-C cable for iPhone 15/16. Order online from Wirely Pakistan.',
    null,
    null,
    '["Supports up to 60W fast charging","High-speed USB 2.0 data transfer (480 Mbps)","1 meter length — ideal for desk & travel","Durable woven design for daily use","Universal USB-C to USB-C compatibility"]'::jsonb,
    '["/products/cable.jpeg"]'::jsonb,
    '[{"icon":"📱","name":"iPhone","models":"iPhone 15, 15 Pro, 16, 16 Pro, 16e"},{"icon":"💻","name":"MacBook","models":"All USB-C MacBooks"},{"icon":"📱","name":"iPad","models":"iPad Pro, iPad Air, iPad Mini (USB-C)"},{"icon":"🎧","name":"AirPods","models":"AirPods Pro 2, AirPods 4 (USB-C)"}]'::jsonb,
    80,
    1,
    true
  ),
  (
    'airpods-pro-2',
    'AirPods Pro 2nd Gen — Active Noise Cancellation',
    'AirPods Pro 2',
    3599,
    null,
    'Popular',
    'AirPods Pro 2nd Generation deliver immersive sound with Active Noise Cancellation and Adaptive Transparency. Featuring the H2 chip for smarter audio, personalised spatial audio, and up to 6 hours of listening on a single charge.',
    'AirPods Pro 2 Pakistan | Wirely',
    'Shop AirPods Pro 2 with ANC in Pakistan. Free delivery, WhatsApp support — Wirely.',
    null,
    null,
    '["Active Noise Cancellation & Adaptive Transparency","H2 chip — smarter audio processing","Personalised Spatial Audio with head tracking","Up to 6hrs listening / 30hrs with case","Touch control + swipe volume on stem","MagSafe & USB-C charging case (IP54)"]'::jsonb,
    '["/products/airpods-pro-2.jpeg","/products/airpods-pro-2-alt.jpeg"]'::jsonb,
    '[{"icon":"📱","name":"iPhone","models":"iPhone 6s and later"},{"icon":"📱","name":"iPad","models":"iPad (5th gen+), iPad Air, iPad Pro"},{"icon":"💻","name":"Mac","models":"MacBook, iMac, Mac Mini (macOS 12.4+)"},{"icon":"⌚","name":"Apple Watch","models":"All Apple Watch models"}]'::jsonb,
    40,
    2,
    true
  ),
  (
    'airpods-4',
    'AirPods 4 — Wireless Charging & ANC',
    'AirPods 4',
    2899,
    null,
    null,
    'AirPods 4 with Active Noise Cancellation bring premium audio to an open-ear design. Powered by the H2 chip, they deliver rich, detailed sound with wireless charging convenience and all-day comfort.',
    'AirPods 4 Pakistan | Wirely',
    'Buy AirPods 4 with ANC and wireless charging in Pakistan. Order from Wirely.',
    null,
    null,
    '["Active Noise Cancellation in open-ear design","H2 chip for powerful computational audio","Personalised Spatial Audio","Up to 30 hours total with wireless charging case","USB-C + wireless (Qi/MagSafe) charging","IP54 dust & water resistance"]'::jsonb,
    '["/products/airpods-4.jpeg","/products/airpods-4-alt.jpeg"]'::jsonb,
    '[{"icon":"📱","name":"iPhone","models":"iPhone 6s and later"},{"icon":"📱","name":"iPad","models":"iPad (5th gen+), iPad Air, iPad Pro"},{"icon":"💻","name":"Mac","models":"MacBook, iMac, Mac Mini (macOS 12.4+)"},{"icon":"⌚","name":"Apple Watch","models":"All Apple Watch models"}]'::jsonb,
    40,
    3,
    true
  ),
  (
    'charger-cable-combo',
    '40W Fast Charger + High-Speed Data Cable',
    'Charger + Cable Combo',
    5198,
    6597,
    'Bundle Deal',
    'The ultimate charging bundle: 40W Dynamic Power Adapter paired with a 60W USB-C cable. Everything you need to fast-charge your iPhone, iPad, or MacBook right out of the box — at a bundled price.',
    '40W Charger + Cable Combo Pakistan | Wirely',
    'Save with the 40W charger and USB-C cable bundle. Free delivery across Pakistan.',
    null,
    null,
    '["Complete charging solution in one box","40W adapter + 60W USB-C cable","Fast charge iPhone 15/16 to 50% in ~30 mins","Perfect for MacBook Air fast charging","Ideal gift set or upgrade kit"]'::jsonb,
    '["/products/combo-charger-cable.jpeg","/products/40w-cable.jpeg"]'::jsonb,
    '[{"icon":"📱","name":"iPhone","models":"iPhone 15, 15 Pro, 16, 16 Pro, 16e"},{"icon":"💻","name":"MacBook","models":"MacBook Air M1/M2/M3"},{"icon":"📱","name":"iPad","models":"iPad Pro, iPad Air (USB-C)"},{"icon":"🎧","name":"AirPods","models":"AirPods Pro 2, AirPods 4 (USB-C)"}]'::jsonb,
    30,
    4,
    true
  )
on conflict (slug) do nothing;
